# Generated by Django 3.0 on 2019-12-20 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0002_auto_20191220_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
