# Generated by Django 3.0 on 2019-12-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0002_auto_20191213_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='characteristic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='gost',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(default='Введите тип ингредиента', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(default='Введите единицу измерения', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='packing',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.Provider'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='purchase_price',
            field=models.FloatField(default=0),
        ),
    ]
