# Generated by Django 3.0 on 2019-12-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0003_auto_20191213_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(default='Введите тип ингредиента', max_length=30),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(default='Введите единицу измерения', max_length=30),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='Введите наименование ингредиента', max_length=30),
        ),
    ]
