# Generated by Django 3.0 on 2019-12-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0003_decoration_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='provider',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='csharp.Provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='characteristic',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ГОСТ'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='packing',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фасовка'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='provider',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='csharp.Provider', verbose_name='Поставщик'),
        ),
    ]
