# Generated by Django 3.0 on 2019-12-14 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0004_auto_20191213_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='delivery_period',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Срок доставки'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default='Поставщик', max_length=100),
        ),
    ]
