# Generated by Django 3.0 on 2019-12-20 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0004_auto_20191220_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='expired',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='expired',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок годности'),
        ),
    ]
