# Generated by Django 3.0 on 2019-12-14 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csharp', '0005_auto_20191214_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='articul',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='characteristic',
            field=models.TextField(blank=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gost',
            field=models.CharField(blank=True, max_length=10, verbose_name='ГОСТ'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(default='Введите тип ингредиента', max_length=30, verbose_name='Тип Ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(default='Введите единицу измерения', max_length=30, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='Введите наименование ингредиента', max_length=30, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='packing',
            field=models.CharField(blank=True, max_length=20, verbose_name='Фасовка'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='csharp.Provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='purchase_price',
            field=models.FloatField(default=0, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(verbose_name='Плановая дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(max_length=200, verbose_name='Наименование заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csharp.Product', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_examples',
            field=models.CharField(max_length=200, verbose_name='Примеры работ'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default='Поставщик', max_length=100, verbose_name='Наименование'),
        ),
    ]
