# Generated by Django 3.0 on 2019-12-14 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csharp', '0006_auto_20191214_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemifinishedSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Количество')),
            ],
        ),
        migrations.DeleteModel(
            name='SemimanufacturesSpecification',
        ),
        migrations.AddField(
            model_name='decoration',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='articul',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='decoration_type',
            field=models.CharField(default='Введите тип украшения', max_length=30, verbose_name='Тип украшения'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='measure_unit',
            field=models.CharField(default='Введите единицу измерения', max_length=30, verbose_name='Единицы измерения'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='name',
            field=models.CharField(default='Введите наименование украшения', max_length=30, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='provider',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.Provider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='purchase_price',
            field=models.FloatField(default=0, verbose_name='Закупочная цена'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес единицы украшения'),
        ),
        migrations.AddField(
            model_name='decorationspecification',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='decorationspecification',
            name='decoration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.Decoration', verbose_name='Украшение для торта'),
        ),
        migrations.AddField(
            model_name='decorationspecification',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.Product', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='characteristic',
            field=models.TextField(blank=True, verbose_name='Характеристика'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.EquipmentType', verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='marking',
            field=models.CharField(default='Введите маркировку', max_length=200, verbose_name='Маркировка'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='equipment_type',
            field=models.CharField(default=1, max_length=200, verbose_name='Маркировка'),
        ),
        migrations.AddField(
            model_name='operationspecification',
            name='equipment_type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.EquipmentType', verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='operationspecification',
            name='num',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='operationspecification',
            name='operation',
            field=models.CharField(default='Введите операцию', max_length=200, verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='operationspecification',
            name='operation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время на операцию'),
        ),
        migrations.AddField(
            model_name='operationspecification',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.Product', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Наименование', max_length=100, verbose_name='Наименование изделия'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='Размеры', max_length=100, verbose_name='Размеры изделия'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.Product', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='provider',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.Provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(blank=True, verbose_name='Плановая дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(blank=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.Product', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_examples',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примеры работ'),
        ),
        migrations.AddField(
            model_name='semifinishedspecification',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='csharp.Product', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='semifinishedspecification',
            name='semifinished',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semifinished', to='csharp.Product', verbose_name='Полуфабрикат'),
        ),
    ]
