# Generated by Django 3.0 on 2019-12-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0006_auto_20191220_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='static/images', verbose_name='Изображение'),
        ),
    ]
