# Generated by Django 3.0 on 2019-12-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0007_auto_20191214_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationspecification',
            name='num',
            field=models.IntegerField(blank=True, default=1, verbose_name='Порядковый номер'),
        ),
    ]
