# Generated by Django 3.0 on 2019-12-17 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0008_auto_20191216_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Введите наименование инструмента', max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('tool_type', models.CharField(default='Введите тип инструмента', max_length=50, verbose_name='Тип инструмента')),
                ('wear_degree', models.CharField(default='Введите степень износа', max_length=50, verbose_name='Степень износа')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата приобретения')),
                ('amount', models.FloatField(default=0, verbose_name='Количество')),
            ],
        ),
        migrations.AlterField(
            model_name='decorationspecification',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='operationspecification',
            name='num',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='operationspecification',
            name='operation_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время на операцию'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='semifinishedspecification',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Количество'),
        ),
    ]
