# Generated by Django 3.0 on 2019-12-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0009_auto_20191217_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorationspecification',
            name='decoration',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='csharp.Decoration', verbose_name='Украшение для торта'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='ingredient',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='csharp.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='semifinishedspecification',
            name='semifinished',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semifinished', to='csharp.Product', verbose_name='Полуфабрикат'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='purchase_date',
            field=models.DateTimeField(verbose_name='Дата приобретения'),
        ),
    ]
