# Generated by Django 3.0 on 2019-12-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0010_auto_20191217_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Отменён', 'Отменён'), ('Составление спеификации', 'Составление спеификации'), ('Подтверждение', 'Подтверждение'), ('Закупка', 'Закупка'), ('Контроль', 'Контроль'), ('Готов', 'Готов'), ('Выполнен', 'Выполнен')], default='Новый', max_length=200, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='decorationspecification',
            name='decoration',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='csharp.Decoration', verbose_name='Украшение для торта'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='ingredient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='csharp.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='semifinishedspecification',
            name='semifinished',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semifinished', to='csharp.Product', verbose_name='Полуфабрикат'),
        ),
    ]
