# Generated by Django 3.0 on 2019-12-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0010_auto_20191220_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationspecification',
            name='equipment_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='csharp.EquipmentType', verbose_name='Тип оборудования'),
        ),
    ]
