# Generated by Django 2.2.8 on 2019-12-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0012_auto_20191222_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decoration',
            options={'verbose_name': 'украшение для торта', 'verbose_name_plural': 'Украшения для торта'},
        ),
        migrations.AlterModelOptions(
            name='decorationspecification',
            options={'verbose_name': 'спецификация украшения для торта', 'verbose_name_plural': 'Спецификации украшения для торта'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='equipmentfailures',
            options={'verbose_name': 'сбой оборудования', 'verbose_name_plural': 'Сбои оборудования'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'тип оборудования', 'verbose_name_plural': 'Типы оборудования'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ингрeдиент', 'verbose_name_plural': 'Ингрeдиенты'},
        ),
        migrations.AlterModelOptions(
            name='operationspecification',
            options={'verbose_name': 'спецификация операции', 'verbose_name_plural': 'Спецификации операции'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'verbose_name': 'спецификация ингредиенты', 'verbose_name_plural': 'Спецификации ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='semifinishedspecification',
            options={'verbose_name': 'спецификация полуфабрикаты', 'verbose_name_plural': 'Спецификации полуфабрикаты'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csharp.EquipmentType', verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='equipmentfailures',
            name='failure_date',
            field=models.DateTimeField(verbose_name='Время начала сбоя'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='equipment_type',
            field=models.CharField(max_length=200, verbose_name='Маркировка'),
        ),
        migrations.AlterField(
            model_name='operationspecification',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csharp.EquipmentType', verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата заказа'),
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('+', '+'), ('-', '-')], default='-', max_length=10, verbose_name='Оценка качества')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csharp.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'контроль качества',
                'verbose_name_plural': 'Контроль качества',
            },
        ),
    ]
