# Generated by Django 2.2.8 on 2020-01-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0013_auto_20191222_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='csharp.EquipmentType', verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='equipmentfailures',
            name='equipment',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='csharp.Equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='operationspecification',
            name='equipment_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='csharp.Tool', verbose_name='Тип оборудования'),
        ),
    ]
