# Generated by Django 2.2.8 on 2020-01-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csharp', '0016_auto_20200125_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csharp.EquipmentType', verbose_name='Тип оборудования'),
        ),
    ]
